# Generated by Django 2.2.10 on 2020-03-11 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20200311_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=50, verbose_name='아이디'),
        ),
    ]