# Generated by Django 2.2.10 on 2020-03-11 10:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('festalist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='festalistkeyword',
            name='user',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
