# Generated by Django 2.2.10 on 2020-03-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festalist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='festalist',
            name='link',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
