# Generated by Django 2.2.10 on 2020-03-02 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festalist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='festalist',
            name='user',
        ),
    ]
