# Generated by Django 2.2.10 on 2020-03-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festalist', '0002_auto_20200305_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='FestaListKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(blank=True, max_length=150)),
            ],
        ),
    ]
