# Generated by Django 2.2.10 on 2020-03-09 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('festalist', '0004_festalistkeyword_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festalistkeyword',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='festalistkeyword',
            name='keyword',
            field=models.CharField(blank=True, max_length=150, unique=True),
        ),
    ]
