# Generated by Django 2.2.10 on 2020-03-09 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festalist', '0005_auto_20200309_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='festalistkeyword',
            old_name='event',
            new_name='user',
        ),
    ]
