# Generated by Django 2.2.10 on 2020-03-09 05:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('festalist', '0006_auto_20200309_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='festalistkeyword',
            name='user',
        ),
        migrations.AddField(
            model_name='festalistkeyword',
            name='user',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
