# Generated by Django 2.2.10 on 2020-03-09 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festalist', '0007_auto_20200309_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festalistkeyword',
            name='keyword',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
