# Generated by Django 2.2.10 on 2020-03-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festalist', '0009_auto_20200309_2104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='festalist',
            options={'ordering': ['-id']},
        ),
        migrations.AddIndex(
            model_name='festalist',
            index=models.Index(fields=['id'], name='festalist_f_id_6514a3_idx'),
        ),
    ]
