# Generated by Django 2.2.10 on 2020-03-12 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festalist', '0010_auto_20200311_2041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='festalist',
            options={'ordering': ['-date', 'id']},
        ),
        migrations.RemoveIndex(
            model_name='festalist',
            name='festalist_f_id_6514a3_idx',
        ),
        migrations.AddIndex(
            model_name='festalist',
            index=models.Index(fields=['date', 'id'], name='festalist_f_date_0662b8_idx'),
        ),
    ]
